<?php if($erreur!=''): ?><div class="alert alert-danger" role="alert"><?=$erreur?></div><?php endif;?>
<?php if(isset($values['id'])):?>
	<form action="editUser.php" method="POST" enctype="multipart/form-data">
	<input type="hidden" name="id" value="<?=$values['id']?>">
<?php else:?>
	<form action="addUser.php" method="POST" enctype="multipart/form-data">
<?php endif;?>
	<div class="form-group row">
		<label for="nom" class="col-sm-2 col-form-label">Nom :</label>
		<div class="col-sm-10">
			<input class="form-control" type="text" value="<?=$values['nom']?>" name="nom" id="nom">
		</div>
	</div>
	<div class="form-group row">
		<label for="prenom" class="col-sm-2 col-form-label">Prénom :</label>
		<div class="col-sm-10">
			<input class="form-control" type="text" value="<?=$values['prenom']?>" name="prenom" id="prenom">
		</div>
	</div>
	<div class="form-group  row">
		<label for="email" class="col-sm-2 col-form-label">Email :</label>
		<div class="col-sm-10">
			<input class="form-control" type="email" value="<?=$values['email']?>" name="email" id="email">
		</div>
	</div>
	<div class="form-group  row">
		<label for="password" class="col-sm-2 col-form-label">Mot de passe :</label>
		<div class="col-sm-4">
			<input class="form-control" type="password" value="" name="password" id="password">
		</div>
		
		<label for="passwordConf" class="col-sm-2 col-form-label">Confirmez :</label>
		<div class="col-sm-4">
			<input class="form-control" type="password" value="" name="passwordConf" id="passwordConf">
		</div>
	</div>
	
	
	
	<input type="submit" value="Enregistrer" class="btn btn-default">
	<input type="reset" value="Réinitialiser" class="btn btn-default">
</form>

