<section class="table-responsive">
    <table id="tableDonnee" class="table">
        <thead>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Email</th>
        </thead>
        <tbody>
            <?php foreach($users as $user):?>
                <tr>
                    <td><?=$user['nom']?></td>
                    <td><?=$user['prenom']?></td>
                    <td><a href="mailto:<?=$user['email']?>"><?=$user['email']?></a></td>
                    <td><a href="editUser.php?id=<?=$user['id']?>"><i class="fas fa-edit"></i></a> <a href="delUser.php?id=<?=$user['id']?>" data-toggle="modal" data-target="#delete"><i class="fas fa-trash-alt"></i></a></td>
                </tr> 
            <?php endforeach;?>
        </tbody>
    </table>
</section>