<!DOCTYPE html>
<html lang="fr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>IPSSI Partiel Project</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <script src="https://kit.fontawesome.com/4a7c807c5e.js"></script>
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Suranna" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Vidaloka&display=swap" rel="stylesheet"> 

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="vendor/css/style.css">

    <!-- Scroll reveal script -->
    <script src="https://unpkg.com/scrollreveal"></script>
    
    
    

  </head>

  <body>

   

    <!-- Page Header -->
    <header>
      <h1><a href="http://locahost:8888/chezflore"> Chez Flore</a> </h1>
    </header>

    <!-- Main Content -->
    <div class="container">
      <?php include('tpl/'.$vue.'.phtml');?>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
    <h3>Contact</h3>
    <article>
      <aside>
        <!-- <h3>Contact</h3> -->
        <p>Mail: <a href="mailto:k.mathe@ecole-ipssi.net">k.mathe@ecole-ipssi.net</a></p>
        <p>Mobile: <a href="tel:+33650193647">+33 (0)6 50 19 36 47</a></p>
        <p><a href="https://www.facebook.com/"><i class="fab fa-facebook-square"></i></a></p>
      </aside>
      <div id="map" style="overflow:hidden;width: 700px;position: relative;"><iframe width="700" height="440" src="https://maps.google.com/maps?width=700&amp;height=440&amp;hl=en&amp;q=apt+(Titre)&amp;ie=UTF8&amp;t=&amp;z=13&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><div style="position: absolute;width: 80%;bottom: 10px;left: 0;right: 0;margin-left: auto;margin-right: auto;color: #000;text-align: center;"><small style="line-height: 1.8;font-size: 2px;background: #fff;"> <a href="https://embedgooglemaps.com/fr/"></a> & <a href="https://newyorkhoponhopoffbus.nl"></a></small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><br />     

      </article>
    </footer>
    <p class="copyright text-muted">MATHE Kevin &copy; - Web Developer - 2019</p>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="vendor/js/script.js"></script>
    <script type="text/javascript">
      ScrollReveal({ distance: '200px' });
      ScrollReveal().reveal('.from-left', { duration: 4000, origin: 'left'});
      ScrollReveal().reveal('.from-right', { duration: 4000, origin: 'right'});
    </script>
  </body>

</html>
